### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/getting-started-with-raspberry-pi-lesson#2]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [ ] hardware.yml
- [ ] software.yml
- [ ] extras.yml
- [x] overview.md
- [x] learn.md
- [x] lesson.md
- [x] ks.md

**Comment by lurch** [comment]
Now that this resource has been converted to the new style, is `teacher-instructions.md` redundant?

**Comment by lawsie** [comment]
Probably - I don't think it's linked to anywhere. However it isn't hurting anyone so I've left it on GitHub. Closing this issue as it is resolved.
