### ISSUE TITLE
Lesson links to "old" video

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/getting-started-with-raspberry-pi-lesson#3]
`lesson-1/lesson.md` says "Watch the official 'What is a Raspberry Pi?' animation." however the video it links to is the *old* one (hosted on YouTube).
http://www.raspberrypi.org/help/what-is-a-raspberry-pi/ points to the *new* version of this video (hosted on Vimeo) which features the [Model B+](http://www.raspberrypi.org/products/model-b-plus/) / Pi 2 style of board, whereas the older YouTube video features the old [Model B](http://www.raspberrypi.org/products/model-b/) style of board.

**Comment by bennuttall** [comment]
Thanks @lurch I've now linked to both the Vimeo and updated YouTube links
